services:
  database:
    image: postgres:14.7
    container_name: objectives-database
    environment:
      - POSTGRES_USER=maria
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=year_objectives
    ports:
      - "5432:5432"
    networks:
      - objective-backend
  liquibase:
    image: liquibase/liquibase:4.27.0
    container_name: objectives-liquibase
    depends_on:
      - database
    restart: "no"
    volumes:
      - ./src/main/resources/liquibase:/liquibase/changelog
    command:
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://database:5432/year_objectives
      - --changeLogFile=./changelog/changelog-master.xml
      - --username=maria
      - --password=password
      - update
    networks:
      - objective-backend
networks:
  objective-backend:
    name: objective-backend
